-- Update users table to match ERD design
ALTER TABLE tb_user
    ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY FIRST,
    ADD COLUMN name VARCHAR(150) NOT NULL AFTER id,
    ADD COLUMN email VARCHAR(255) UNIQUE NOT NULL AFTER name,
    ADD COLUMN role VARCHAR(50) DEFAULT 'customer' NOT NULL AFTER password,
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER role,
    DROP PRIMARY KEY,
    ADD CONSTRAINT uk_tb_user_email UNIQUE (email);